version: '3.8'

services:
  otragh-mongodb:
    image: mongo
    container_name: otragh-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
    name: otragh_mongodb_data